"""LangGraph state definition for the Scientific Articles Engine.

This module defines the shared state that flows through the multi-agent workflow.
"""

from typing import Annotated

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

from ..models.article import Article
from ..models.paper import Paper
from ..models.review import ReviewResult
from ..models.visualization import Visualization


class AgentState(TypedDict):
    """State schema for the LangGraph workflow.

    This state is passed between agents and modified as the workflow progresses.
    Uses TypedDict for type safety and LangGraph state management.

    Attributes:
        topic: Research topic provided by the user
        papers: List of papers found by the searcher agent
        outline: Article outline generated by searcher
        article: Draft article generated by writer
        review: Quality review from reviewer agent
        visualizations: Generated diagrams and tables
        revision_count: Number of writer-reviewer iteration cycles
        quality_passed: Whether the article passed quality review
        searcher_approved: HITL flag - user approved sources and outline
        final_approved: HITL flag - user approved final article
        error_message: Error message if any step fails
        messages: Conversation history (for LangGraph compatibility)
    """

    # Core data
    topic: str
    papers: list[Paper]
    outline: str | None
    article: Article | None
    review: ReviewResult | None
    visualizations: list[Visualization]

    # Workflow control
    revision_count: int
    quality_passed: bool
    searcher_approved: bool
    final_approved: bool

    # Error handling
    error_message: str | None

    # LangGraph message history (using add_messages reducer)
    # Annotated: This field uses the add_messages reducer to maintain the conversation history.
    # List[BaseMessage]: Maintains the conversation history for LangGraph agents
    # add_messages: Reducer function to update the message history
    messages: Annotated[list[BaseMessage], add_messages]


def create_initial_state(topic: str) -> AgentState:
    """Create initial state for a new workflow run.

    Args:
        topic: Research topic to investigate

    Returns:
        Initialized AgentState with default values
    """
    return AgentState(
        topic=topic,
        papers=[],
        outline=None,
        article=None,
        review=None,
        visualizations=[],
        revision_count=0,
        quality_passed=False,
        searcher_approved=False,
        final_approved=False,
        error_message=None,
        messages=[],
    )
