"""Pydantic models for generated articles."""

from pydantic import BaseModel, Field


class ArticleSection(BaseModel):
    """Section within an article.

    Attributes:
        title: Section heading
        content: Section text content
        subsections: Nested subsections (for hierarchical structure)
    """

    title: str = Field(..., description="Section title/heading")
    content: str = Field(..., description="Section text content")
    subsections: list["ArticleSection"] = Field(
        default_factory=list, description="Nested subsections"
    )


class Article(BaseModel):
    """Generated scientific article.

    Represents the complete article generated by the writer agent,
    potentially revised based on reviewer feedback.

    Attributes:
        title: Article title
        abstract: Article abstract
        sections: List of article sections (Introduction, Methods, etc.)
        references: List of cited papers
        word_count: Total word count
        version: Version number (increments with revisions)
        revision_notes: Notes from revisions (if applicable)
    """

    title: str = Field(..., description="Article title")
    abstract: str = Field(..., description="Article abstract")
    sections: list[ArticleSection] = Field(..., description="Article sections")
    references: list[str] = Field(default_factory=list, description="List of references")
    word_count: int = Field(..., description="Total word count")
    version: int = Field(default=1, description="Version number")
    revision_notes: str | None = Field(None, description="Revision notes")

    class Config:
        """Pydantic model configuration."""

        json_schema_extra = {
            "example": {
                "title": "A Survey of Transformer Architectures",
                "abstract": "This article surveys recent advances in transformer architectures...",
                "sections": [
                    {
                        "title": "Introduction",
                        "content": "Transformers have revolutionized...",
                        "subsections": [],
                    },
                    {
                        "title": "Background",
                        "content": "The original transformer model...",
                        "subsections": [],
                    },
                ],
                "references": [
                    "Vaswani et al. (2017). Attention Is All You Need.",
                    "Devlin et al. (2018). BERT: Pre-training...",
                ],
                "word_count": 3500,
                "version": 1,
            }
        }

    def to_markdown(self) -> str:
        """Convert article to Markdown format.

        Returns:
            Markdown-formatted article text
        """
        md_parts = [
            f"# {self.title}\n",
            f"**Abstract**: {self.abstract}\n",
            "---\n",
        ]

        for section in self.sections:
            md_parts.append(self._section_to_markdown(section, level=2))

        if self.references:
            md_parts.append("\n## References\n")
            for i, ref in enumerate(self.references, 1):
                md_parts.append(f"{i}. {ref}\n")

        return "\n".join(md_parts)

    def _section_to_markdown(self, section: ArticleSection, level: int) -> str:
        """Convert a section to Markdown recursively.

        Args:
            section: Section to convert
            level: Heading level (2 = ##, 3 = ###, etc.)

        Returns:
            Markdown-formatted section
        """
        heading = "#" * level
        md = f"{heading} {section.title}\n\n{section.content}\n\n"

        for subsection in section.subsections:
            md += self._section_to_markdown(subsection, level + 1)

        return md
